### ISSUE TITLE
Repository contains no version tags

### ISSUE THREAD

**Issue by JochenHiller** [eclipse/concierge#10]
Migrated from Eclipse Bugzilla #499055

Jochen Seeber 2016-08-02 11:35:07 EDT

> Hi,
> 
> the Git repo does not contain any tagged versions, however, there are public releases. This really prevents us from using concierge, since we need reliable and repeatable builds.
> 
> Regards,
> Jochen

Comment 1 Jan S. Rellermeyer 2016-08-02 11:37:49 EDT

> Thanks for reminding me of this issue, I totally forgot. I created a local tag when we released but I could not get it pushed (I believe Gerrit was the problem) and I simply forgot to research further how to get it done. 
> I will do it now.

**Comment by rellermeyer** [comment]
With the move to GitHub (and abandoning Gerrit) I could finally push the tag.
