### ISSUE TITLE
REST support

### ISSUE THREAD

**Issue by JochenHiller** [eclipse/concierge#11]
Migrated from Eclipse Bugzilla #475520

Jan S. Rellermeyer 2015-08-20 13:57:14 EDT

> Add the REST service and Java REST client to Concierge as optional bundles.

Comment 1 Jan S. Rellermeyer 2015-09-19 01:28:36 EDT

> awaiting decision on https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10150
> Also requires https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10152 and https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10153
> Moving to RC1.

Comment 2 Jan S. Rellermeyer  2015-10-20 00:27:52 EDT

> Not in 5.0.0 release timeframe anymore. 
> 
> We can do a 5.1 release that includes REST.

**Comment by rellermeyer** [comment]
REST support fully implemented and integrated.
