### ISSUE TITLE
Publish Concierge R5 to Maven repos (repo.eclipse.org, Maven Central)

### ISSUE THREAD

**Issue by JochenHiller** [eclipse/concierge#18]
We have to publish our releases (R5) to common used maven repositories, e.g. maven central.
Requested by the community and needed for integration in other projects

**Comment by enolgor** [comment]
Hi, I would really like this to happen. What is the status on this issue?

**Comment by rellermeyer** [comment]
I think this is still blocked on the problem of Jar-signing. Maybe Jochen can add more insights.

**Comment by joerg-wille** [comment]
I want to use concierge in a maven based bnd project. could not find a recent Concierge artefact on any public maven site. what is the status? what needs to be done?

**Comment by JochenHiller** [comment]
Hi Joerg,
unfortunately we did not had yet the time to publish the Concierge
artifacts neither to Eclipse Maven repo nor to Maven Central.
As Jan said, it is about the build process and signing the artifacts.
I am struggeling with the Eclipse infrastructure and did not have the time
to fix that.
I will see if I can start again this week.
Bye, Jochen

**Comment by enolgor** [comment]
I would really appreciate as well if it was uploaded to the central repository. I really like concierge but for my build process it's really convenient that all the artifacts are downloaded from a remote maven repository. Right now I had to upload it to a private remote repository, but in the long term it would be very helpful to be in the central repository.

**Comment by joerg-wille** [comment]
Hi Jochen,
great to get such a fast response. As I understood you, not the signing process with gradle is giving you problems, but the Eclipse infrastructure, right? I have no knowledge of the latter but if I can help with anything, let me know.
Thanks, Jörg

**Comment by svilenvul** [comment]
It would be great to see Concierge in a public Maven repository.

**Comment by tverbele** [comment]
As of release 5.1 we now have our artifacts on Maven Central: https://search.maven.org/search?q=g:org.eclipse.concierge
