### ISSUE TITLE
Starting bundles with start level >3 does not work

### ISSUE THREAD

**Issue by JochenHiller** [eclipse/concierge#4]
Migrated from Eclipse Bugzilla #481659

Jochen Hiller 2015-11-08 04:56:42 EST

> When fixing https://bugs.eclipse.org/bugs/show_bug.cgi?id=481650 I added test cases with more start level options.
> 
> One test case fails if bundles with start levels of 10, 20, 30 will be installed. But these bundles could not be started, they simple ignore bundle.start().
> See test case at http://git.eclipse.org/c/concierge/org.eclipse.concierge.git/tree/org.eclipse.concierge/test/org/eclipse/concierge/compat/service/XargsFileLauncherXargsTest.java#n140
> 
> I saw that this will happen since using a start level of 4.

**Comment by JochenHiller** [comment]
I will take care of testing and fixing of that issue for Milestone 5.1 release

**Comment by JochenHiller** [comment]
I checked that issue, and fixed the test cases: if bundles with start level >3 should be started automatically, we have to set the property `org.osgi.framework.startlevel.beginning` to a higher value

**Comment by rellermeyer** [comment]
Yes, this makes a lot of sense.
You can also programmatically set the start level through the corresponding service.

—Jan.

On Nov 19, 2017, at 10:52 AM, Jochen Hiller <notifications@github.com<mailto:notifications@github.com>> wrote:


I checked that issue, and fixed the test cases: if bundles with start level >3 should be started automatically, we have to set the property org.osgi.framework.startlevel.beginning to a higher value

**Comment by JochenHiller** [comment]
Start levels does work fine, test case was wrong.
Close that issue now.
