### ISSUE TITLE
BundleWiring.listResources(...) does not consider embedded JARs

### ISSUE THREAD

**Issue by sjka** [eclipse/concierge#52]
When asking a bundle for its contained resources via `bundle.adapt(BundleWiring.class).listResources(...)`, the content of embedded JARs is not considered. 

I have to admit that so far I couldn't spot anything in the OSGi specs which explicitly states that it _should_ do so - I merely noticed that this works on equinox. I have a corresponding test case in [sjka/concierge@testListResources](https://github.com/sjka/concierge/commits/testListResources).

I'd be happy if any of you experts could have a quick look and advise on this.

**Comment by sjka** [comment]
PS: The best I could find is this from `BundleWiring.listResources(...)`'s JavaDoc:

> Returns the names of resources visible to this bundle wiring's class loader

As the stuff within the JARs _is_ visible to the class loader, _my_ assumption was that it _should_ work.

**Comment by JochenHiller** [comment]
I added a PR now to fix this issue.
I also re-run the TCK. There is the same test case failing as before doing the change.

The failing test case is related to a somehow related problem:
`org.osgi.test.cases.framework.junit.wiring.BundleWiringTests.testListResources`

I will look into that further on. But the test case from @sjka does work now.

@rellermeyer Can you do a careful review of that?
