### ISSUE TITLE
Concierge CI (snapshot) builds not running

### ISSUE THREAD

**Issue by svilenvul** [eclipse/concierge#61]
Latest snapshots of Eclipse Concierge are not available in http://download.eclipse.org/concierge/download/snapshots/?d.

Last successful build is from 2018 05 23.

Migrated from - https://github.com/eclipse/concierge/issues/59#issuecomment-431411085

**Comment by JochenHiller** [comment]
Thanks for hint. I will take care about

**Comment by tverbele** [comment]
Build is fixed, there are new snapshots up there!

**Comment by svilenvul** [comment]
Thank you all!
