### ISSUE TITLE
Resolution failed Exception with Import-Package org.osgi.framework.wiring;version="[1.2,2)"

### ISSUE THREAD

**Issue by derryx** [eclipse/concierge#78]
Hi!

I am running Concierge 5.1.0 and have an Import-Package dependency in my bundle to 

org.osgi.framework.wiring;version="[1.2,2)"

and get a Resolution failed Exception. Is something wrong with this version number? This is the version exported by the system bundle.

CU
Thomas

**Comment by tmarkwardt** [comment]
Hi derryx,

Concierge 5.1.0 support the version 1.1.0 on org.osgi.framework.wiring 

Regards

**Comment by derryx** [comment]
Thanks tmarkwardt,

after changing to [1.1,2) it works.

Thanks for your fast response
Thomas
