### ISSUE TITLE
Broken links on website

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/concierge#82]
Hi guys,

I just noticed that a couple of your links on the website result in a 404:
- "Downloads" in the top menu: https://projects.eclipse.org/projects/rt.concierge/downloads
- "OSGi R5" in the last paragraph: https://www.osgi.org/Release5/HomePage

**Comment by tverbele** [comment]
Should be fixed

**Comment by kaikreuzer** [comment]
Indeed 👍
