### ISSUE TITLE
Concierge does not support EXPORT_SERVICE/Export-Service?

### ISSUE THREAD

**Issue by hengyunabc** [eclipse/concierge#86]
https://github.com/eclipse/concierge/search?q=EXPORT_SERVICE&unscoped_q=EXPORT_SERVICE

**Comment by tmarkwardt** [comment]
Hi,
since OSGI V4 the manifest entry "Export-Service" is deprecated.
Concierge as "simple" OSGI implementation does not support this manifest entry.
I think we don't implement a deprecated function.
Regards
Torsten

**Comment by hengyunabc** [comment]
> Hi,
> since OSGI V4 the manifest entry "Export-Service" is deprecated.
> Concierge as "simple" OSGI implementation does not support this manifest entry.
> I think we don't implement a deprecated function.
> Regards
> Torsten

Thanks.
